SYNONYM_MAP = {
    "python": ["python"],
    "java": ["java"],
    "c++": ["c++", "cpp"],
    "javascript": ["javascript", "js", "node.js", "nodejs"],
    "typescript": ["typescript", "ts"],
    "sql": ["sql", "postgres", "mysql", "sqlite", "oracle"],
    "bash": ["bash", "shell scripting", "shell", "sh"],
    "go": ["go", "golang"],
    "rust": ["rust"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning", "dl"],
    "nlp": ["nlp", "natural language processing", "text mining"],
    "computer vision": ["computer vision", "cv", "image recognition", "object detection"],
    "tensorflow": ["tensorflow", "tf"],
    "pytorch": ["pytorch", "torch"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "keras": ["keras"],
    "huggingface": ["huggingface", "transformers", "bert", "gpt"],
    "openai": ["openai", "chatgpt", "gpt-3", "gpt-4"],
    "data analysis": ["data analysis", "data analytics", "exploratory data analysis", "eda"],
    "data science": ["data science", "data scientist"],
    "data engineering": ["data engineering", "etl", "data pipelines", "airflow", "spark"],
    "statistics": ["statistics", "statistical analysis"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "matplotlib": ["matplotlib", "seaborn", "visualization"],
    "cloud": ["cloud", "aws", "azure", "gcp", "google cloud", "microsoft azure", "cloud computing"],
    "docker": ["docker", "containerization"],
    "kubernetes": ["kubernetes", "k8s"],
    "devops": ["devops", "ci/cd", "jenkins", "github actions", "pipeline", "deployment"],
    "terraform": ["terraform", "iac", "infrastructure as code"],
    "linux": ["linux", "ubuntu", "centos", "redhat"],
    "rest api": ["rest api", "restful api", "api development"],
    "graphql": ["graphql"],
    "microservices": ["microservices", "microservice architecture"],
    "oop": ["oop", "object oriented programming"],
    "system design": ["system design", "architecture", "scalability", "design patterns"],
    "agile": ["agile", "scrum", "kanban", "sprint"],
    "full stack": ["full stack", "frontend", "backend", "fullstack"],
    "react": ["react", "react.js", "reactjs"],
    "vue": ["vue", "vue.js", "vuejs"],
    "django": ["django"],
    "flask": ["flask"],
    "spring": ["spring", "spring boot"],
    "git": ["git", "version control", "github", "gitlab"],
    "debugging": ["debugging", "troubleshooting"],
    "testing": ["testing", "unit testing", "integration testing", "pytest", "junit"],
    "design": ["design", "ux", "ui", "user experience", "wireframe", "prototyping"],
    "leadership": ["leadership", "team lead", "mentoring", "collaboration"],
    "communication": ["communication", "written communication", "verbal communication"],
}
